---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  name: devops-toolkit
  namespace: argocd
spec:
  destination:
    namespace: production
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: networking.istio.io
    jsonPointers:
    - /spec/http
    kind: VirtualService
  project: production
  source:
    helm:
      values: |
        image:
          repository: bmutziu/devops-toolkit
          tag: 19b1fbc
        ingress:
          enabled: false
          host: devops-toolkit.54.194.74.173.xip.io
        istio:
          enabled: true
        hpa: true
        rollout:
          enabled: true
      version: v3
    path: helm
    repoURL: https://github.com/bmutziu/devops-toolkit.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
